### PR TITLE
Major update (work in progress)

### PR DESCRIPTION
**Pull request by HiFiiDev**
Hello.   This update adds the following:
• a more automated install
• installs a custom packages if they aren't already installed
• added comments for part of the code
• my attempt at improvise the scripts
• formatted using beautysh

This took me hours and hours.  Please at least cherry pick this and run the script? 👎

### CODE REVIEW

**Comment by HiFiiDev** [comment]
Here is the script in action:
https://photos.app.goo.gl/4azESZuTCGQ1qtiy7

**Comment by thelearn-tech** [comment]
I am new here , I love your installation script I pretty .

**Comment by HiFiiDev** [comment]
> I am new here , I love your installation script I pretty .

Hey! I was hoping you would respond.  Glad you finally did. :)

I am glad you like it.  I'm still working on it! I stopped temporarily though because I wasnt sure if you were going to be open to it.  More to come soon 👍

**Comment by thelearn-tech** [comment]
Do and check install.sh file I already updated it

**Comment by HiFiiDev** [comment]
Nice!!

**Pull request closed without merging**
